builds:
  - env:
      - CGO_ENABLED=0
    binary: goreleaser-testing
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
    files:
      - completions/*
      - README.md

before:
  hooks:
    - chmod +x ./scripts/completions.sh
    - ./scripts/completions.sh
      
brews:
  - name: goreleaser-testing
    homepage: https://github.com/MaxwelMazur/homebrew-tools
    tap:
      owner: MaxwelMazur
      name: homebrew-tools
    install: |
      bin.install "goreleaser-testing"
      bash_completion.install "completions/goreleaser-testing.bash" => "goreleaser-testing"
      zsh_completion.install "completions/goreleaser-testing.zsh" => "_goreleaser-testing"
      fish_completion.install "completions/goreleaser-testing.fish" 

nfpms:
  - id: packages
    license: MIT
    package_name: goreleaser-testing
    maintainer: MaxwelMazur
    homepage: https://github.com/MaxwelMazur/goreleaser-testing
    bindir: /usr/local/bin
    formats:
      - apk
      - deb
      - rpm
  - contents:
    - src: completions/goreleaser-testing.bash
      dst: /usr/share/bash-completion/completions/goreleaser-testing
      file_info:
        mode: 0644
    - src: completions/goreleaser-testing.fish
      dst: /usr/share/fish/vendor_completions.d/goreleaser-testing.fish
      file_info:
        mode: 0644
    - src: /completions/goreleaser-testing.zsh
      dst: /usr/share/zsh/vendor-completions/_goreleaser-testing
      file_info:
        mode: 0644

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Env.BIN_VERSION }}_{{ .Env.BIN_VERSION }}"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

aurs:
  - description: Deliver Go binaries as fast and easily as possible
    maintainers:
      - 'Maxwel Mazur'
    license: MIT
    git_url: 'ssh://aur@aur.archlinux.org/goreleaser-testing-bin.git'
    package: |
      # bin
      install -Dm755 "./goreleaser-testing" "${pkgdir}/usr/bin/goreleaser-testing"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "completions/goreleaser-testing.bash" "${pkgdir}/usr/share/bash-completion/completions/goreleaser-testing"
      install -Dm644 "completions/goreleaser-testing.zsh" "${pkgdir}/usr/share/zsh/site-functions/_goreleaser-testing"
      install -Dm644 "completions/goreleaser-testing.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/goreleaser-testing.fish"
