name: Deploy to Stage

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.17
    env:
      CGO_ENABLED: 0 # Statically linked

    steps:
      - name: Setting GIT
        run: git config --global url."https://${{ secrets.GLOBAL_TOKEN }}:x-oauth-basic@github.com/aziontech".insteadOf "https://github.com/aziontech"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_ver
        uses: anothrNick/github-tag-action@1.37.0
        env:
          RELEASE_BRANCHES: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Refresh git
        run: git fetch --tags

      - name: set bin_version environment variable 
        run: echo "BIN_VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: trest
        run: mkdir dist && touch dist/test.txt
      
      - name: testing step above
        run: echo "${{ env.BIN_VERSION }}"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

